services:
    odiseo_sylius_avatax_plugin.event_listener.admin.menu_builder:
        class: Odiseo\SyliusAvataxPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    odiseo_sylius_avatax_plugin.event_listener.avatax_aware_listener:
        class: Odiseo\SyliusAvataxPlugin\Mapping\AvataxAwareListener
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: 99 }
